---
title: "Practica Programa 1 Limpieza Datos Netflix"
author: "Carolina Durán Villalta"
date: "2023-07-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(readxl)
library(tidyr)# doma de datos
library(janitor) #limpieza de datos
library(lubridate)
library(hms)
library(gt)
library(datasets)
```

```{r}
datos_netflix <- read_csv2("https://raw.githubusercontent.com/isa229/programacion_analisis_datos_ii/main/netflix_info.csv")
```

```{r}
datos_netflix <- datos_netflix |>
 rename(
   "Id_programa" = show_id,
    "Tipo" =  type,
   "Título"  =  title,
    "Director" = director,
   "País" = country,
   "Fecha_agregada" = date_added,
   "Año_de_lanzamiento" = release_year,
   "Clasificación" = rating,
   "Duración" = duration,
   "Listado_en" = listed_in
    )
```

```{r}
informacion_duplicada <- datos_netflix |>
  janitor::get_dupes()
```

```{r}
datos_netflix |>
  janitor::get_dupes(Título, Id_programa) |> 
  select(Título, Id_programa, dupe_count) |> 
  distinct()
```

```{r}
informacion_duplicada <- datos_netflix |> 
distinct()
```

```{r}
datos_sin_vacios <- informacion_duplicada |> 
  remove_empty(which = c("rows", "cols")) 
```

```{r}
datos_sin_año_de_lanzamiento <- select(datos_sin_vacios,-Año_de_lanzamiento)
```

```{r}
datos_sin_año_de_lanzamiento<- datos_sin_año_de_lanzamiento  |>
  mutate(across(c(Tipo), function(x) ifelse(x == "movie", "Movie", x))) |>
  mutate(across(c(Tipo), function(x) ifelse(x == "tv show", "TV Show", x))) |>
  mutate(across(c(Tipo), function(x) ifelse(x == "Movi", "Movie", x))) 
```

```{r}
 datos_sin_año_de_lanzamiento<- datos_sin_año_de_lanzamiento |>
  mutate(País = ifelse(País == "united states", "United States", País)) |>
    mutate(País = ifelse(País == "United State", "United States", País)) |>
  mutate(País = ifelse(País== "india", "India", País)) |>
  mutate(País = ifelse(País == "pakistan", "Pakistan", País)) |> 
  mutate(País = ifelse(País == "canada", "Canada", País)) 
```

```{r}
datos_sin_año_de_lanzamiento <- datos_sin_año_de_lanzamiento|> 
  mutate(Tipo = replace_na(Tipo, "Sin información"),
         Director= replace_na(Director, "Sin información"),
         País = replace_na(País, "Sin información"),
         Título = replace_na(Título, "Sin información"))
```

```{r}
datos_finales_netflix <- datos_sin_año_de_lanzamiento |> 
  mutate(Fecha_agregada = mdy(Fecha_agregada))
```

```{r}
glimpse(datos_finales_netflix)

```
```{r}
datos_finales_netflix <- datos_finales_netflix |> 
  mutate(Anyo = year(Fecha_agregada))
```

```{r}
datos_finales_netflix <- datos_finales_netflix |> 
  mutate(Mes = month(Fecha_agregada))
```

```{r}
Movies <- datos_finales_netflix %>%
  filter(Tipo == "Movie")
```

```{r}
Top_10_directores_peliculas <- Movies %>%
  group_by(Director) %>%
  summarise(Conteo = n()) %>%
  arrange(desc(Conteo)) %>%
  top_n(10)
```

```{r}
Show <- datos_finales_netflix %>%
  filter(Tipo == "TV Show")
```

```{r}
Top_10_directores_shows <- Show %>%
  group_by(Director) %>%
  summarise(Conteo = n()) %>%
  arrange(desc(Conteo)) %>%
  top_n(9) 

#profe aquí si ponía 10, me tiraba la lista de todos los shows, por eso puse 9 
```

```{r}
datos_pelis_shows_marzo_2020<- datos_finales_netflix |> 
  filter(Tipo %in% c("Movie","TV Show" ) , Anyo == 2020, Mes == 3)
```

